/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solucion6;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnumpalabras = new javax.swing.JTextField();
        txtnumcm = new javax.swing.JTextField();
        txtnumcolores = new javax.swing.JTextField();
        txtcostopalabras = new javax.swing.JTextField();
        txtcostotamaño = new javax.swing.JTextField();
        txtcostocolores = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmdcalcular = new javax.swing.JButton();
        cmdborrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("COBRO POR AVISO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 170, 30));

        txtnumpalabras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumpalabrasKeyTyped(evt);
            }
        });
        getContentPane().add(txtnumpalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 60, -1));

        txtnumcm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumcmKeyTyped(evt);
            }
        });
        getContentPane().add(txtnumcm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 60, -1));

        txtnumcolores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumcoloresKeyTyped(evt);
            }
        });
        getContentPane().add(txtnumcolores, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 60, -1));

        txtcostopalabras.setEditable(false);
        txtcostopalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcostopalabrasActionPerformed(evt);
            }
        });
        getContentPane().add(txtcostopalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 100, -1));

        txtcostotamaño.setEditable(false);
        getContentPane().add(txtcostotamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 100, -1));

        txtcostocolores.setEditable(false);
        getContentPane().add(txtcostocolores, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 100, -1));

        jLabel2.setText("Numero de palabras");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, -1));

        jLabel3.setText("Tamaño");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 70, -1));

        jLabel4.setText("numero de colores");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, -1));

        cmdcalcular.setText("CALCULAR");
        cmdcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcalcularActionPerformed(evt);
            }
        });
        getContentPane().add(cmdcalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        cmdborrar.setText("BORRAR");
        cmdborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdborrarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jLabel5.setText("Total");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        txttotal.setEditable(false);
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcalcularActionPerformed
      double np,tm,nc,cp,cm,cc,total;
      String res1,res2,res3,res4;
      
       if(txtnumpalabras.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite numero de palabras","Error", JOptionPane.ERROR_MESSAGE);
         txtnumpalabras.requestFocusInWindow();
     }else if(txtnumcolores.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite numero de colores","Error", JOptionPane.ERROR_MESSAGE);
         txtnumcolores.requestFocusInWindow();
     }else if(txtnumcm.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite tamaño en  centimetros","Error", JOptionPane.ERROR_MESSAGE);
         txtnumcm.requestFocusInWindow();
     }else{
      
      
      np=Double.parseDouble(txtnumpalabras.getText());
      tm=Double.parseDouble(txtnumcm.getText());
      nc=Double.parseDouble(txtnumcolores.getText());
      
      cp=np*20000;
      cm=tm*15000;
      cc=nc*25000;
      
      total=cp+cm+cc;
      
     res1= String.valueOf(cp);
     txtcostopalabras.setText(res1);
     res2 = String.valueOf(cc);
     txtcostocolores.setText(res2);
     res3 = String.valueOf(cm);
     txtcostotamaño.setText(res3);
     res4 = String.valueOf(total);
     txttotal.setText(res4);
     }
    }//GEN-LAST:event_cmdcalcularActionPerformed

    private void txtcostopalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcostopalabrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcostopalabrasActionPerformed

    private void cmdborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdborrarActionPerformed
     txtnumpalabras.setText("");
     txtnumcm.setText("");
     txtnumcolores.setText("");
     txtcostopalabras.setText("");
     txtcostocolores.setText("");
     txtcostotamaño.setText("");
     txttotal.setText("");
     
     
     
     txtnumpalabras.requestFocusInWindow();
    }//GEN-LAST:event_cmdborrarActionPerformed

    private void txtnumpalabrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumpalabrasKeyTyped
    char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              
              evt.consume(); 
                      
          } 
    }//GEN-LAST:event_txtnumpalabrasKeyTyped

    private void txtnumcmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumcmKeyTyped
     char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              
              evt.consume(); 
                      
          } 
    }//GEN-LAST:event_txtnumcmKeyTyped

    private void txtnumcoloresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumcoloresKeyTyped
      char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              
              evt.consume(); 
                      
          } 
    }//GEN-LAST:event_txtnumcoloresKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdborrar;
    private javax.swing.JButton cmdcalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtcostocolores;
    private javax.swing.JTextField txtcostopalabras;
    private javax.swing.JTextField txtcostotamaño;
    private javax.swing.JTextField txtnumcm;
    private javax.swing.JTextField txtnumcolores;
    private javax.swing.JTextField txtnumpalabras;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
